### PR TITLE
Apple Silicon support

### LINKED ISSUE #10: Apple Silicon support
Are there any plans to support Apple Silicon CPUs such as the M1?

### PR DESCRIPTION
**Pull request by Wendor**
## Pull Request

Fixes #10 

#### Changes proposed:

* [x] Fix
* [ ] Enhancement
* [ ] Remove
* [ ] Update

#### Description (what is this PR about)

* Adds cpu temperature SMC keys for Apple Silicon M1 (used if process.arch == 'arm64')
* Adds support for "flt" datatype

### CODE REVIEW

**Comment by Wendor** [comment]
изображение

**Comment by Wendor** [comment]
Ooops... push force automatically close PR.

**Comment by sebhildebrandt** [comment]
@Wendor ... AWESOME!!! Thank you so much! Version 1.0.8 just released!

**Comment by Wendor** [comment]
@sebhildebrandt you are welcome ;-)

**Comment by 3rror404** [comment]
This doesn't seem to work for me on M1.  

```
"osx-temperature-sensor": "^1.0.8",
"systeminformation": "^5.11.15",
```

```
const si = require('systeminformation');

(async () => {
    console.log(await si.cpu());
    console.log(await si.cpuTemperature());
})();
```

```
{
  manufacturer: 'Apple',
  brand: 'M1',
  vendor: 'Apple',
  family: '458787763',
  model: '',
  stepping: '2',
  revision: '',
  voltage: '',
  speed: 2.4,
  speedMin: 2.4,
  speedMax: 2.4,
  governor: '',
  cores: 8,
  physicalCores: 8,
  performanceCores: 4,
  efficiencyCores: 4,
  processors: 1,
  socket: 'SOC',
  flags: '',
  virtualization: false,
  cache: { l1d: 131072, l1i: 65536, l2: 4194304, l3: null }
}
{ main: -1, cores: [], max: -1 }
```

Running on a Mac mini M1 2020. MacOS 12.4

**Comment by Wendor** [comment]
@3rror404 Can you try run this and share cpu temperature keys?
https://github.com/dkorunic/iSMC

изображение

**Comment by 3rror404** [comment]
Here you go @Wendor ...

Screenshot 2022-07-18 at 12 33 02

**Comment by 3rror404** [comment]
Here you go @Wendor ...
Screenshot 2022-07-18 at 12 40 36

My results look _very_ different to yours.

I don't know if this is helpful at all but I did come across a couple of other projects that claim to be able to read CPU temp on M1 (I haven't tested them)...

https://github.com/andreivcodes/coolm1
https://github.com/fermion-star/apple_sensors

**Comment by Wendor** [comment]
> Here you go @Wendor ...
> 
> Screenshot 2022-07-18 at 12 33 02

@3rror404 Looks like previous version 1.0.7 should works on your system. Can you check?

**Comment by 3rror404** [comment]
Unfortunately 1.0.7 doesn't work for me either. Exactly the same output as 1.0.8

```
{ main: -1, cores: [], max: -1 }
```

**Comment by Wendor** [comment]
@3rror404 First screen was wrong?

**Comment by sebhildebrandt** [comment]
When I am back in my office I can also check sone other machines. On my M1 MacBook Pro, latest OS version (Monterey) this works perfectly.

**Comment by Wendor** [comment]
Seems like we need add new smc datatype "hid".
But i can't test code (i have only M1 Pro on macOS Ventura 13).

**Comment by 3rror404** [comment]
> @3rror404 First screen was wrong?

Sorry, yes. The first screenshot I shared was from my Intel Mac because I'm an idiot :)

**Comment by 3rror404** [comment]
> But i can't test code (i have only M1 Pro on macOS Ventura 13).

I'm here if you need a tester.

**Comment by sebhildebrandt** [comment]
@3rror404 thank you for offering your help here! 
@Wendor ... anything we can do on our side? I also have 2 different M1 machines where I am able to test it ... on my M1 MacBook Pro all works fine ... MacMini: I did not yet testet it there but of course I can provide results if you need something.

**Comment by Wendor** [comment]
@3rror404 @sebhildebrandt ... information about temperature in this case we can't get from smc.. :(
We need another C module for node like this https://github.com/freedomtan/sensors/blob/master/sensors/sensors.m .
I can try make this module works, but need free time for this. I try make this module on this week.
And this be difficult for me, I not C/C++/ObjC developer))

**Pull request merged**
